name: pyvo
channels:
  - defaults
  - open3d-admin
dependencies:
  - ipykernel
  - ipympl
  - ipython
  - ipywidgets
  - matplotlib
  - pillow
  - pip
  - python=3.8
  - scikit-image
  - scipy
  - open3d
  - scikit-learn
  - pip:
    - numpy
    - opencv-python
    - plyfile
    - tqdm
    - sklearn
    - addict
    - pandas
